### ISSUE TITLE
Can't setup ember-model-validator

### ISSUE THREAD

**Issue by minchomilev** [esbanarango/ember-model-validator#13]
Hi,
I can't get the model inside the router,
I am getting an error:
TypeError: fakeModel is undefined
or
TypeError: fakeModel.validate is not a function

also I am using ember-mirage as a single mock server.

**Comment by esbanarango** [comment]
@minchomilev Could you share your code pls.

Also `fakeModel` is just an example, you have to replace that with your __real__ model.

**Comment by minchomilev** [comment]
Hi,
I have a working example with ember-validations inside the controller
and now I am trying to make validations inside the model, without success
this is my repo:
https://github.com/minchomilev/ember-validations-example

**Comment by esbanarango** [comment]
@minchomilev Were you able to set up it?
