### ISSUE TITLE
`errors` is a proxy object with no length

### ISSUE THREAD

**Issue by charlesfries** [esbanarango/ember-model-validator#178]
I am attempting to iterate over the errors array on a model, inside an .hbs template. When I log `model.errors`, I get back a proxy object with zero length. Is this intentional? Is there a way to read the errors array in the template without using `.get()`?

The .hbs templates usually seem to automatically resolve these proxy objects asynchronously over time but it's not happening for me.

```
DEBUG: -------------------------------
DEBUG: Ember             : 3.25.4
DEBUG: Ember Data        : 3.25.0
DEBUG: Ember Simple Auth : 3.1.0
DEBUG: Model Fragments   : 5.0.0-beta.2
DEBUG: -------------------------------
```

**Comment by esbanarango** [comment]
Hey @charlesfries look like you just closed this issue... Did you figure out the issue?

**Comment by charlesfries** [comment]
Hi @esbanarango thanks for the reply, I was able to figure it out. Just needed to look at the `errors` property on each one of my models--for some reason I thought the `errors` array on one model would include the relation errors as well. Thanks!
