### ISSUE TITLE
model.validate() causes error 

### ISSUE THREAD

**Issue by ollar** [esbanarango/ember-model-validator#185]
Hello!

I've got an empty model that I've just created in a Route#model hook. When I run `model.validate()` on that model it crashes with on error:

```
Uncaught Error: Attempted to handle event `becameError` on <user:null> while in state root.loaded.created.uncommitted. 
```

```
import Model, { attr } from '@ember-data/model';
import Validator from 'ember-model-validator/decorators/model-validator';


@Validator
class UserModel extends Model {
    @attr('string', {defaultValue: ''}) username;
    @attr('string', {defaultValue: ''}) password;

    validations = {
        username: {
            presence: true
        },
        password: {
            presence: true,
        }
    }
}

export default UserModel;
```

**Comment by esbanarango** [comment]
@ollar could you provide more info about the `ember-data` and the `ember-source` versions you're using 🙏

**Comment by ollar** [comment]
Sure,

```
DEBUG: ------------------------------- 
DEBUG: Ember                 
DEBUG: Ember Data            
DEBUG: Ember Model Validator 
DEBUG: -------------------------------
```

**Comment by ollar** [comment]
Here is a minimum app - https://github.com/ollar/model-validator-demo

**Comment by tdwesten** [comment]
I have the same problem, my versions are: 

Ember | 3.25.4
Ember Data | 3.28.4
Ember Model Validator | 3.10.0

**Comment by tdwesten** [comment]
Oké I did same digging and I think you need to add a "error" when calling  recordWasInvalid like  ```store.recordWasInvalid(recordModel, errors, 'error');```

**Comment by esbanarango** [comment]
👋 . This has been fixed on https://github.com/esbanarango/ember-model-validator/releases/tag/v.3.13.0
