### ISSUE TITLE
ember-global deprecation warning on 3.28

### ISSUE THREAD

**Issue by skaterdav85** [esbanarango/ember-model-validator#188]
Hello!

If you create a new 3.28 app with the following: 

```bash
npx ember-cli@3.28 new my-app --yarn
ember install ember-model-validator
ember s
```

You'll get a deprecation warning for [ember-global](https://deprecations.emberjs.com/v3.x/#toc_ember-global):

![image](https://user-images.githubusercontent.com/687449/147691384-0fb59491-a986-48a0-b88e-e42739552867.png)

Would be happy to help upgrade this if you need the help. :)

**Comment by esbanarango** [comment]
@skaterdav85 Thank you for reporting it. A fix for that warning has been already merged: https://github.com/esbanarango/ember-model-validator/pull/186 I'll be releasing the new version this week 🙏

**Comment by esbanarango** [comment]
Version `3.12.0` released
https://github.com/esbanarango/ember-model-validator/releases/tag/v3.12.0
