### ISSUE TITLE
Ember Data 2.1 compatibility with belongsTo?

### ISSUE THREAD

**Issue by corrspt** [esbanarango/ember-model-validator#19]
Hey!

I'm working with ember-model-validator and EmberData 2.1 and I'm having an issue validating a belongsTo relationship. I'm using version 1.1.0 of ember-model-validator

I've create my model like the following

```js
import DS from 'ember-data';
import Ember from 'ember';
import Validator from 'weldnote/mixins/model-validator';

const { computed, isEmpty, inject } = Ember;
const { belongsTo } = DS;

export default DS.Model.extend(Validator, {
  i18n: inject.service(),
  code: belongsTo('industry-code', { async: false }),
 
  validations: {
    code: {
      presence: true
    }
  }

});

```

When I call validate() the `code` is considered to be empty (but it's not).
I've managed to debug the issue to the following:

```js
//model-validator.js
_validatePresence: function _validatePresence(property, validation) {
      var propertyValue = this.get(property);
      // If the property is an async relationship.
      if (this._modelRelations() && !Ember['default'].isBlank(this._modelRelations()[property])) {
        propertyValue = this.get(property + '.content'); // Here is the problem
      }
      if (Ember['default'].isBlank(propertyValue)) {
        this.set('isValidNow', false);
        this._addToErrors(property, validation.presence, Messages['default'].presenceMessage);
      }
    },
```

If I console.log `propertyValue`, right before the `this.get(property + .content')` I get the following
`Class {store: Class, container: Container, _internalModel: ember$data$lib$system$model$internal$model$$InternalModel, isError: false, adapterError: (...)`

But the this.get(property + '.content') returns undefined.... was it this way with older versions of Ember Data (I'm guessing that's my problem).

I've been dealing with this through custom validations, but it's kind of annoying to always do this:

```js
validations: {
    code: {
      custom: {
        validation(key, value, model) {
          let id = model.get('code.id');
          return !isEmpty(id);
        }, message(key, value) {
          let translation = value.translate('edit-view.attributes.required');
          return translation;
        }
      }
    }
```

Thanks a lot for the project. It's been very helpful

**Comment by esbanarango** [comment]
@corrspt Thanks for reporting this bug. It should be fixed now. Could you confirm on your end.

**Comment by corrspt** [comment]
@esbanarango - Thank you so much for fixing it insanely fast. I confirm that it's fixed, thanks again! I was able to delete a lot of code because of that :+1:

**Comment by esbanarango** [comment]
So glad it helped you! :beers:
