### ISSUE TITLE
Potential Feature: Validate from template function

### ISSUE THREAD

**Issue by csprocket777** [esbanarango/ember-model-validator#197]
**Feature Request:**
Allow the ability to validate a model from the template without needing javascript

**Reason:**
I have models that will need to be validated across the app. My current understanding of the process is that I need to call a custom function in javascript from the template to allow the model's `validate()` function to be called properly.

**Implication:**
This means I need to have a validate function everywhere I want to call `model.validate()` from.

**Proposed:**
Allow:
`<ButtonComponent clickAction={{myModel.validate}}/>`

**Current HACKY workaround:**
My models all extend from a custom base-model class I've defined. In this class I'm including an `@action` handler to call the model's `validate()` function.

Example:
```javascript
import Model from '@ember-data/model';
import { action } from '@ember/object';

export default class BaseModel extends Model {
  get errorReadout():String {
    return this.errors.map(errObj=>{
      return htmlSafe(`${errObj.message.join(", ")}`)
    }).join(". ")
  }

  @action
  templateValidate(){
    this.validate();
  }
}

declare module 'ember-data/types/registries/model' {
  export default interface ModelRegistry {
    'base-model': BaseModel;
  }
}

```

This allows me to do the following in my template:
```handlebars
<MyCustomTextInputField
  @label="My input label" 
  @value={{myModel.name}}
  @hasError={{gt myModel.errors.length 0}}
  @hintText={{if (gt myModel.errors.length 0) myModel.errorReadout}}
  @key-up={{myModel.templateValidate}}
  @focus-out={{myModel.templateValidate}}
></MyCustomTextInputField>
```

I'm sure there are issues with this (happy to learn and adapt), but this approach feels DRY.

**Comment by esbanarango** [comment]
@csprocket777 This is a great idea, I think we could probably add a [Template Helper](https://guides.emberjs.com/release/components/helper-functions/#toc_writing-a-helper-function) where we can pass the model. Something like:

```js
<MyCustomTextInputField
  @key-up={{validate-model myModel}}
  @focus-out={{validate-model myModel}}
></MyCustomTextInputField>

```
