### ISSUE TITLE
Inject Validator into `DS.Model`.

### ISSUE THREAD

**Issue by esbanarango** [esbanarango/ember-model-validator#2]
Model validator shouldn't be a mixin but part of the DS.Model object by default.

**Comment by dmuneras** [comment]
@esbanarango it is not as simple as I thought.

**Comment by mkay581** [comment]
I actually think a mixin can be more appropriate in certain cases. If we do add this feature, it should be configurable.

**Comment by esbanarango** [comment]
@mkay581 Right, this is no longer wanted.
