### ISSUE TITLE
Internationalization support (i18n)?

### ISSUE THREAD

**Issue by corrspt** [esbanarango/ember-model-validator#20]
Hi

Is there a way to add i18n support for the default error messages (like "can't be blank"). Especially if it would work with ember-i18n :) ?

**Comment by esbanarango** [comment]
@corrspt I haven't worked with ember-i18n yet, so I'm not familiar with it. But all the default messages are [here](https://github.com/esbanarango/ember-model-validator/blob/master/addon/messages.js). You could eaither overwrite those messages on your models, or we could also have one `messages.js` file per language. I'm willing to implement this feature, just don't know yet which should be the best approach to tackle it.

**Comment by corrspt** [comment]
I was thinking of having a messages.js file per language, as I'm interested in having support for multiple languages in an application.

Ideally, I would want to let ember-model-validator to know what my current locale is (like passing a computed property or something so that ember-model-validator could 'watch' or 'depend' on it) and when my locale changes, whenever a new messages needs to be displayed it would get that locale and use the correct file.

Sorry for not having a better suggestion at the moment. I'll try to come up with some ideas if I'm able to. Thanks for the availability to help :)

**Comment by gzurbach** [comment]
If anything it should be an `ember-i18n-model-validator` addon, which would make the bridge between `ember-model-validator` and `ember-i18n`.

The reason is that `ember-model-validator` shouldn't be dealing with language inheritance ('en' vs 'en-us' for instance). `ember-i18n` does that very well :)

See i18n support in `ember-cp-validations`: http://offirgolan.github.io/ember-cp-validations/docs/modules/I18n%20Solutions.html

**Comment by GabrielCW** [comment]
I'm interested in this to be supported, especially interpolated values.

At the minute, how can I get a given parameter in a message? For instance, this doesn't work:

```javascript
  validations: {
    title: {
      length: {
        minimum: {
          value: 5,
          message: 'This must be at least {{value}} characters long'
        }
      }
    }
  }
```

Is there a way to do something like this currently?

**Comment by esbanarango** [comment]
@GabrielCW interpolated values will be supported on the next version, coming out this weekend. Right now you can use `custom message`:

````js
validations: {
  title: {
    length: {
      minimum: {
        value: 5,
        message: : function(key, value, _this){
          return `This must be at least ${value} characters long`
        }
      }
    }
  }
}
```

**Comment by esbanarango** [comment]
@GabrielCW interpolated values are now supported on version `2.7.0`. Now you can do:

````js
  validations: {
    title: {
      length: {
        minimum: {
          value: 5,
          message: 'This must be at least {value} characters long'
        }
      }
    }
  }
````
