### ISSUE TITLE
InternalModel removed in ember 4.6

### ISSUE THREAD

**Issue by dani3lsz** [esbanarango/ember-model-validator#208]
Unfortunately, it seems that ember data InternalModel is removed, see [4.6 release notes](https://blog.emberjs.com/ember-4-6-released), and since the core and model validators use it, the tests are failing, after updating to ember 4.6.
```
TypeError: this._internalModel.getRecord is not a function
           at n.clearErrors
           at n.validate
           at Object.<anonymous> 
```

**Comment by esbanarango** [comment]
@dani3lsz Version 4.0.0 https://github.com/esbanarango/ember-model-validator/releases/tag/v4.0.0 has been released.
