### ISSUE TITLE
Error with ember-model-validator@4.4.0 and ember 4.6+

### ISSUE THREAD

**Issue by eliel-jr** [esbanarango/ember-model-validator#238]
Unfortunately, even with the fixes released in version ember-model-validator@4.4.0 continues to throw errors when using with ember 4.6+.

```
TypeError: this._internalModel.transitionTo is not a function
    at CoreValidator.pushErrors (model-validator.js:23:29)
    at CoreValidator.validate (core-validator.js:133:29)
```

this._internalModel object is still available, so some functions have been removed.

**Comment by esbanarango** [comment]
@eliel-jr could you try version `4.5.0`
