### ISSUE TITLE
numericality validator assumes presence

### ISSUE THREAD

**Issue by guruofgentoo** [esbanarango/ember-model-validator#25]
If I put a numericality validator on one of my nullable number fields, validation will fail if input is blank. The validator should not assume the behavior of the presence validator; presence should be specified separately.

**Comment by esbanarango** [comment]
@guruofgentoo you can set the `allowBlank` option to true.
````js
myNumber:{
    numericality: {onlyInteger: true, allowBlank: true}
}
````

**Comment by guruofgentoo** [comment]
Quite so; I missed that detail, so this issue is closed.

However, it seems more intuitive to use multiple validators instead of setting options on a single one. Explicit > implicit.
