### ISSUE TITLE
Emtpy value as invalid property

### ISSUE THREAD

**Issue by Exelord** [esbanarango/ember-model-validator#26]
HI,
I noticed that if I have:
```
logoUrl: {
  URL:true,
},
```
It required from me value cuz empty string or `null` is always invalid. Is there an option for make any empty string or null always valid?

**Comment by esbanarango** [comment]
Hello @Exelord. You can use `allowBlank`.

````js
logoUrl: {
  URL: {allowBlank: true}
},
````

**Comment by Exelord** [comment]
Thank you! :+1:
