### ISSUE TITLE
Length : different messages for "too long" and "too short"

### ISSUE THREAD

**Issue by GabrielCW** [esbanarango/ember-model-validator#28]
Hello there!
First, let me thank you for this very good addon!

Concerning error messages for the length constraint, is there a way to have different messages for minimum and maximum?
Something like this would be great:

```javascript
length: {
    minimum: {
        value: 3,
        message: 'form.errors.tooShort'
    }
}
```

**Comment by esbanarango** [comment]
@GabrielCW Version `1.5.0` now supports the message option for `minimum` and `maximum`.
Like this:

````js

smallName:{
  length: {
    maximum: {
      value: 3,
      message: 'should be smaller'
    }
  }
}
````

**Comment by GabrielCW** [comment]
Brilliant, thanks! I sure will

**Comment by GabrielCW** [comment]
I tried it, it does exactly what I needed! Thank you!
