### ISSUE TITLE
Add a Demo app.

### ISSUE THREAD

**Issue by esbanarango** [esbanarango/ember-model-validator#29]

**Comment by bryanhickerson** [comment]
Not sure if this is the right ticket for it, but sample handlebars code would be great. I'm curious how you are displaying the errors in the fields for the live demo.

**Comment by dmuneras** [comment]
I can do it if you want @esbanarango

**Comment by esbanarango** [comment]
@bryanhickerson I can point you to the components we use for rendering the errors: 

#### object-form component.
[object-form.js](https://github.com/esbanarango/ember-model-validator/blob/master/tests/dummy/app/components/object-form.js) / [object-form.hbs](https://github.com/esbanarango/ember-model-validator/blob/master/tests/dummy/app/templates/components/object-form.hbs)

#### form-field component.
[form-field.js](https://github.com/esbanarango/ember-model-validator/blob/master/tests/dummy/app/components/form-field.js) / [form-field.hbs](https://github.com/esbanarango/ember-model-validator/blob/master/tests/dummy/app/templates/components/form-field.hbs)


##### Example:
````js
{{#object-form for=model classNames="segment"}}
  {{#form-field for='fullName' label="Full Name" required=true}}
    {{input value=model.fullName placeholder="Full Name"}}
  {{/form-field}}
{{/object-form}}
````

Let me know if it's clear enough.

**Comment by bryanhickerson** [comment]
That was perfect, thanks!
