### ISSUE TITLE
Add priority errors message

### ISSUE THREAD

**Issue by AntonyDeveau** [esbanarango/ember-model-validator#31]
First, thanks for your library it help me a lot.

Second, is there a way to prioritize errors message. For example, i have a too short message and a required message to show. 

I would like to show "Requiredt" when its empty, not both. And if it too short, only "Too short".

Thanks man !

**Comment by esbanarango** [comment]
@AntonyDeveau We don't actually have support for prioritization on the error messages. In this case you would have to handle this situation when displaying the errors. Either showing only the first one on the `errors` array or checking that array and selecting the one you want to show. Anyway, if have a solution that could be integrated into the addon, please don't hesitate to contribute.
