### ISSUE TITLE
how do you do a custom validation on a relationship?

### ISSUE THREAD

**Issue by NullVoxPopuli** [esbanarango/ember-model-validator#32]
I see that there is the relation: ['belongsTo']
but I want to only check for the relation if a different relationship's property is true

**Comment by NullVoxPopuli** [comment]
I have this currently:

```
        custom: {
          message: 'Level is required for the selected ticket.',
          // value may be a promise here
          // so we need to see if we can access the
          // id property on it
          validation(key, value, model){
            let requiresLevel = model.get('package.requiresTrack');
            debugger;
            if (requiresLevel){
              // value is undefined, and level is a promise
              return Ember.isPresent(model.get('level'));
            }

            return true;
          }
        }
```

**Comment by esbanarango** [comment]
@NullVoxPopuli You need to add that validation directly on the relation. Could you show me your entire model.

**Comment by NullVoxPopuli** [comment]
here is the model: https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/models/attendance.js#L66

here is how I'm validating it: https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/services/order-cart.js#L153

(I'm just calling `validate()` on the `attendance`)

**Comment by esbanarango** [comment]
@NullVoxPopuli Looking at your code. Seems like the `attendance` model doesn't have the `level` relation, are you using there an `attendance` or an `event-attendance` (which is the one with the realtion) ?
The validation looks good and should be working as you have it there.

**Comment by NullVoxPopuli** [comment]
Oh! The validation probably needs too be on event-attenndance! I'll try that

**Comment by esbanarango** [comment]
@NullVoxPopuli Let me know if that works so I can close this issue. Thank you.

**Comment by NullVoxPopuli** [comment]
Ok, so I finally move the level validation to the event-attendance:

![image](https://cloud.githubusercontent.com/assets/199018/14763602/57bbafca-0968-11e6-9a42-ff907aa850e9.png)

So maybe it's just a logic thing. Cause if I change my isPresent check to be on `model.get('level.id')`, it works just fine ('throws' a validation error via `validate()`)

**Comment by NullVoxPopuli** [comment]
Though, I think it would be great to have bulit in `if: ` keys on the relationship validators, like, I would like to do:

```javascript
validations: {
  level: { 
    presence: true,
    if: 'model.package.requiresTrack'
  }
}
```

**Comment by NullVoxPopuli** [comment]
also, it appears validations get extended from superclass to subclass :-\ I'll open that as a seperate issue
