### ISSUE TITLE
A Subclass' validations override the superclass' validations

### ISSUE THREAD

**Issue by NullVoxPopuli** [esbanarango/ember-model-validator#33]
To reproduce:

on super class:
- validate one field

on sub class:
- validate a different field

test:
- have an instance of the sub class
- do something that you would expect to cause both validations to fail
- there is only an error for the subclass's validation, and not the superclass

**Comment by esbanarango** [comment]
This shouldn't be an issue anymore with the decorator approached we introduced in version 3.8
