### ISSUE TITLE
WARNING: Interacting with a record errors object will no longer change the record state.

### ISSUE THREAD

**Issue by esbanarango** [esbanarango/ember-model-validator#35]

**Comment by brandonjmckay** [comment]
Any ideas how to work around this?

**Comment by arthur5005** [comment]
This sounds pretty fundamental, seems to stem from calling ```clear()``` on the errors collection in the ```validate()``` method.
Any action on this?

**Comment by c0achmcguirk** [comment]
As a quick and dirty way you could replace:

```javascript
// Clean all the current errors
this.get('errors').clear();
```

With this:

```javascript
// Clean all the current errors
this._internalModel.clearErrorMessages()
```

But that's probably worse than what the deprecation warning is about.

It was deprecated in [this commit](https://github.com/emberjs/data/commit/0057b0435f1f484b20d93f1db4ea88c26d3f4b17).
