### ISSUE TITLE
Validation with inherit

### ISSUE THREAD

**Issue by AntonyDeveau** [esbanarango/ember-model-validator#36]
Hi,

I have a model 'property' and 'flat'.
Flat inherits from property, but when i declare validations in both, only 'Flat' validators show, because they are rewritten.
How can I use validations from the parent in the child class?

**Comment by esbanarango** [comment]
#33

**Comment by GabrielCW** [comment]
@AntonyDeveau and I came across a solution for simple cases of inheritance. It goes no further than exporting and merging validation properties, but it's a start.

Here's an example:

``parent.js``
```javascript
export let validations = {
  aFieldInTheParent: {
    presence: {message: 'This field must be there'}
};

export default Resource.extend({
  aFieldInTheParent: DS.attr('string'),
  validations: validations
});
```

``child.js``
```javascript
import Parent from './parent';
import { validations } from './parent';

export default Parent.extend({
  aFieldInTheChild: DS.attr('number'),
  validations: Ember.merge(validations, {
    aFieldInTheChild: {
      numericality: {
        greaterThan: 0,
        message: 'This must be greater than 0.'
      }
    }
  })
});
```

Note that we haven't tested whether added validations on then parent's fields in the child work. This depends on how Ember.merge works, although this can be overriden by your own merging logic.

Hope that may help someone (@NullVoxPopuli)

**Comment by NullVoxPopuli** [comment]
thanks for the merging idea!

**Comment by GabrielCW** [comment]
Turns out merging as I wrote it actually changed the parent's validations to get the child's.
Validations should be copied first, like so:

``child.js``
```javascript
import Parent from './parent';
import { parentValidations } from './parent';

export default Parent.extend({
  aFieldInTheChild: DS.attr('number'),
  validations: Ember.merge(Ember.copy(parentValidations, true), {
    aFieldInTheChild: {
      numericality: {
        greaterThan: 0,
        message: 'This must be greater than 0.'
      }
    }
  })
});
```
