### ISSUE TITLE
WARNING: Interacting with a record errors object will no longer change the record state.

### ISSUE THREAD

**Issue by datasc123** [esbanarango/ember-model-validator#37]
I did not get ember-model-validator to work, I did the following in my model:

```
export default Model.extend(Validator,{
  login: attr(),
  password: attr(),
  
  validations: {
    login: {
         presence: true
    }
  },
```

I get the warning when I am creating a new user:

`WARNING: Interacting with a record errors object will no longer change the record state.`

**Comment by esbanarango** [comment]
Hello @datasc123. Please use least version (`2.2.0`) this issue was solved there.
