### ISSUE TITLE
Is there something similar to a conditional validation?

### ISSUE THREAD

**Issue by Gorzas** [esbanarango/ember-model-validator#40]
I need to validate a field only if another attribute has an specific value and I don't know if the library has this option.

i.e. something like this:

```
validations: {
  images: {
    presence: true,
    validateIf: function () { return 'gallery' === this.get('type'); }
  }
}
```

I know I can do it with customValidators so I can solve it that way right but it feels better this way because I can reuse the base validations of the library. Does this exists? If not, I can check the code and add it with a PR.

**Comment by esbanarango** [comment]
@Gorzas conditional validations will be supported on the next version coming out this weekend.

**Comment by esbanarango** [comment]
@Gorzas You can now use _conditional validation_ option `if` like this:
````js
validations: {
  images: {
    presence: {
      if: function(key, value, _this) {
        return 'gallery' === _this.get('type');
      }
    }
  }
}
`````

Just upgrade to versio `2.6.0`.

**Comment by Gorzas** [comment]
Thanks a lot @esbanarango :D
