### ISSUE TITLE
Document how to use the error-list in a template

### ISSUE THREAD

**Issue by fknoll** [esbanarango/ember-model-validator#42]
I have set out to give `ember-model-validator` a serious try-out. It would be very helpful for me, if the documentation included an example (best practice) about **how to use the error-list in a template.**

For instance, look at the example at http://esbanarango.github.io/ember-model-validator/#/validators/length.

![image](https://cloud.githubusercontent.com/assets/8566293/18580669/35dcf38e-7bfd-11e6-8cd9-cd8c40609f0a.png)

**Here, it is possible to trigger several errors at the same time - great!**

**How** do you relate errors for a specific model attribute to the field displaying this attribute? Are you using computed properties**?**

**How** do you make the error-messages immediately disappear from display and error-list, when starting to type something into a specific error-prone field, while all other errors keeps existing in the error-list and keeps being displayed**?**

**Comment by esbanarango** [comment]
Hello @fknoll 

**ember-model-validator** uses `DS.ERRORS CLASS` from the `ember-data module`, so these errors are the same errors you would get when your backend responds with any errors. 

You have many options to print the errors in your template. The most basic way to do it is documented here: http://emberjs.com/api/data/classes/DS.Errors.html

> Errors can be displayed to the user by accessing their property name to get an array of all the error objects for that property. Each error object is a JavaScript object with two keys:
>
> `message` A string containing the error message from the backend
> `attribute` The name of the property associated with this error message

Example from the document:

```hbs
<label>Username: {{input value=username}} </label>
{{#each model.errors.username as |error|}}
  <div class="error">
    {{error.message}}
  </div>
{{/each}}

<label>Email: {{input value=email}} </label>
{{#each model.errors.email as |error|}}
  <div class="error">
    {{error.message}}
  </div>
{{/each}}
