### ISSUE TITLE
Upgrading to ember data 2.15 trigger this WARNING: Interacting with a record errors object will no longer change the record state

### ISSUE THREAD

**Issue by nizarayari** [esbanarango/ember-model-validator#58]
Hi there,

I just upgraded ember-data, ember-cli and ember-source to 2.15 and I got this message from my model validator. Could you plz help me to find a solution on this issue?

**Comment by esbanarango** [comment]
@nizarayari that's a warning we should be fine with it. We will work on preventing that warning message on the next release.

**Comment by nizarayari** [comment]
ok thanks
