### ISSUE TITLE
Doesn't validate belongsTo async relation

### ISSUE THREAD

**Issue by sescobb27** [esbanarango/ember-model-validator#7]
I have the following model

```js
import DS from 'ember-data';
import Validator from '../mixins/model-validator';

var attr = DS.attr;

export default DS.Model.extend(Validator, {
  plan: DS.belongsTo('plan', {async: true}),
  validations: {
    plan: {
      presence: {
        message: 'Please select a plan'
      }
    }
  }
});
```
Then when I'm trying to validate a model trying to test the behavior when the validation fail, the validation pass, but if I delete the `{async: true}` the validations doesn't pass (as expected)

**Comment by esbanarango** [comment]
@sescobb27 Right now `async relations` aren't supported to be validated. One thing you could try, is resolving that promise before calling `.validate()`.

**Comment by esbanarango** [comment]
@sescobb27 did it work resolving the promise before validating?

**Comment by sescobb27** [comment]
not yet, I just remove the `{async: true}` to make it work, the object isn't that big to make it async

**Comment by esbanarango** [comment]
@sescobb27 `belongsTo` async relations are now supported!
