### ISSUE TITLE
Issues when dealing with ember data states

### ISSUE THREAD

**Issue by sescobb27** [esbanarango/ember-model-validator#9]
in https://github.com/esbanarango/ember-model-validator/blob/master/addon/mixins/model-validator.js#L38

you are making a transition to the state `updated.uncommitted` and that set model properties to  `isNew == false` and `isDirty == true` breaking the API like this: https://gist.github.com/sescobb27/5becc19ba451a18f5e15

a workaround to fix that problem is this, but it isn't generic for all situations.

```js
if (!order.get('id')) {
  if (order.get('currentState.stateName') === 'root.loaded.updated.uncommitted') {
    order.transitionTo('loaded.created.uncommitted');
  }
  return order.save().then(deferred.resolve);
}
```

I think you should save the previous state of the model, and when the model is valid again reset that state

**Comment by esbanarango** [comment]
@sescobb27 Could you check the new version pls.

**Comment by sescobb27** [comment]
Fixed, thanks :)

**Comment by esbanarango** [comment]
:+1:
